import csv
from rdkit import Chem
from rdkit.Chem import AllChem
import os

def optimize_molecule(mol):
    """为分子添加氢原子并进行3D结构嵌入和力场优化"""
    try:
        mol_with_h = Chem.AddHs(mol)
        AllChem.EmbedMolecule(mol_with_h, AllChem.ETKDG())
        AllChem.MMFFOptimizeMolecule(mol_with_h)
        return mol_with_h
    except Exception as e:
        print(f"优化分子时发生错误：{e}")
        return None

def smiles_to_xyz(no, smiles, output_dir):
    """将SMILES码转换为.xyz文件并保存到指定目录"""
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        print(f"无法从SMILES码 '{smiles}' 创建分子对象")
        return
    
    optimized_mol = optimize_molecule(mol)
    if optimized_mol is None:
        return
    
    # 将分子对象转换为.xyz格式
    xyz_filename = f"{no}.xyz"
    xyz_filepath = f"{output_dir}/{xyz_filename}"
    with open(xyz_filepath, 'w') as xyz_file:
        xyz_file.write(f"{len(optimized_mol.GetAtoms())}\n")
        xyz_file.write("Generated by RDKit\n")
        conf = optimized_mol.GetConformer()
        for i, atom in enumerate(optimized_mol.GetAtoms()):
            symbol = atom.GetSymbol()
            pos = conf.GetAtomPosition(i)
            xyz_file.write(f"{symbol} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}\n")

def process_csv_file(csv_file, output_dir):
    """处理CSV文件，提取SMILES码并生成.xyz文件"""
    with open(csv_file, 'r') as file:
        reader = csv.reader(file)
        next(reader)  # 跳过标题行
        for row in reader:
            no = row[0]  # 编号在第一列
            smiles = row[1]  # SMILES码在第二列
            smiles_to_xyz(no, smiles, output_dir)

# 设置CSV文件路径和输出目录
csv_file_path = r'/home/ubuntu/cal/DPSCAL/lunci3/merged-lunci3.csv'  # 替换为您的CSV文件路径
output_directory = r'/home/ubuntu/cal/DPSCAL/lunci3/xtb-1'  # 替换为您的输出目录路径

# 确保输出目录存在
if not os.path.exists(output_directory):
    os.makedirs(output_directory)

# 处理CSV文件
process_csv_file(csv_file_path, output_directory)
